# Generated by Django 3.0.7 on 2020-10-23 06:17

from django.db import migrations, models
import django.db.models.deletion
import jornadas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=55)),
                ('apellido_pat', models.CharField(max_length=35)),
                ('apellido_mat', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=125)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=jornadas.models.nombre_foto)),
            ],
            options={
                'db_table': 'entidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jordana', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=65)),
                ('inicio', models.TimeField()),
                ('termino', models.TimeField()),
            ],
            options={
                'db_table': 'jornada',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'turno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('password', models.IntegerField(db_column='pass')),
                ('id_entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jornadas.Entidad')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso', models.DateTimeField(null=True)),
                ('salida', models.DateTimeField(null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jornadas.Entidad')),
                ('id_jordana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jornadas.Jornada')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jornadas.Turno')),
            ],
            options={
                'db_table': 'asistencia',
                'managed': True,
            },
        ),
    ]
